sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t mjondocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mjondocker/docker-react npm run test

deploy:
  provider: azure_web_apps
  username: AZURE_WA_USERNAME
  password: AZURE_WA_PASSWORD
  site: AZURE_WA_SITE
  edge: 
  verbose: true
