sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t mjondocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mjondocker/docker-react npm run test